#!markdown

# Exceptions: The failwith Function

The `failwith` function generates an F# exception.

## Syntax

#!fsharp

failwith error-message-string


#!markdown

## Remarks

The <em>error-message-string</em> in the previous syntax is a literal string or a value of type `string`. It becomes the `Message` property of the exception.

The exception that is generated by `failwith` is a `System.Exception` exception, which is a reference that has the name `Failure` in F# code. The following code illustrates the use of `failwith` to throw an exception.

#!fsharp

let divideFailwith x y =
  if (y = 0) then failwith "Divisor cannot be zero."
  else
    x / y

let testDivideFailwith x y =
  try
     divideFailwith x y
  with
     | Failure(msg) -> printfn "%s" msg; 0

let result1 = testDivideFailwith 100 0


#!markdown

## See also

